name: Varnasi Mobile App Build
run-name: ${{ github.actor }} pushed to ${{ github.ref_name }} triggering mobile app build ğŸš€
on:
  push:
    branches:
      - main
      - develop
      - 11-chore-cicd-pipeline

env:
  PROPERTIES_PATH: "./android/key.properties"
jobs:
  Androi-App-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ secrets.STORE_FILE }} >> ${{env.PROPERTIES_PATH}}
      - run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/key.jks
      - run: flutter pub get
      - run: flutter build apk --flavor prod
